10 eliminate blocking code
Northeastern-Electric-Racing/Embedded_Code pull request #14
Opened 2022-08-09 15:51 UTC by nwdepatie

Small change, I just removed the 5ms delay between sending out CAN messages, I want to test to see if it is necessary but if it isn't it should speed things up. I also removed a 1000 ms delay every time the car starts up/TS is cycled which might have been causing the weird startup

2022-08-09 22:44 UTC, rydzynskip commented
We probably shouldn't do this. It will just be flooding the CAN bus because it doesn't seem like there is any delay from when the main loop calls mpu.sendMCMsg() till when the command message is sent. The MC docs say that any delay in the range of 10-50 ms between command messages is good for most use cases, and we are at 5ms.

2022-08-10 06:29 UTC, mccauleyma requested changes
Agreeing with @rydzynskip . You're gonna send infinite messages. Unless I'm missing something, rather than making this non-blocking you've just removed the CAN_CMD_DELAY control

2022-08-10 06:29 UTC, mccauleyma commented on MPU/src/cascadiamc.cpp
> -        Serial.println("CUCK");
YOU CANNOT REMOVE CUCK

2022-08-10 06:29 UTC, mccauleyma commented on MPU/src/cascadiamc.cpp
> +    {
This will go infinitely fast, using up all fault clear attempts and realistically only sending one message

2022-08-10 06:29 UTC, mccauleyma commented on MPU/src/cascadiamc.cpp
> +    {
Or Ig maybe not, but still kinda weird. Fault clear attempts should probably be spaced by at least 0.25 seconds

2022-08-10 06:29 UTC, mccauleyma commented on MPU/src/cascadiamc.cpp
> -    while(!motorCommand_wait.isTimerExpired()){}
Why are you removing all these delays completely? I thought the goal was to make them non-blocking, not non-existant

2022-08-12 00:21 UTC, nwdepatie commented
Oops, I will reimplement the timer for can_cmd_delay

2022-09-18 18:23 UTC, closed without merging